# ----------- These are disabled for the moment as they take several minutes to build ----------------
# ----------- TODO: Re-evaluate usefulness of hacky work arounds for multi-os testing ----------------
#matrix:
#  include:
#    - name: "Python 3.7.4 on macOS"
#      os: osx
#      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
#      language: shell       # 'language: python' is an error on Travis CI macOS
#    - name: "Python 3.7.4 on Windows"
#      os: windows           # Windows 10.0.17134 N/A Build 17134
#      language: shell       # 'language: python' is an error on Travis CI Windows
#      before_install:
#        - choco install python
#        - python -m pip install --upgrade pip
#      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
#  allow_failures:
#    - name:
#      - "Python 3.7.4 on macOS"
#      - "Python 3.7.4 on Windows"
# ----------------------------------------------------------------------------------------------------

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
before_install:
  - sudo apt update
  - sudo apt install -f -y smbclient
# command to install dependencies
install:
  - pip3 install pytest-cov
  - pip3 install coveralls
  - pip3 install -r requirements.txt
# command to run tests
script:
  - pytest --cov-config=.coveragerc --cov=./
after_success:
  - coveralls