# Test on Linux and Windows
os:
  - linux
  - windows

# Windows might be a bit dodgy, allow failures on it
matrix:
  allow_failures:
    - os: windows

language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
after_success:
  - coveralls